In [5]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

# 1. Api z .env
load_dotenv()
api_key = os.getenv("COINGECKO_API_KEY")

# 2. URL Z API
url = "https://api.coingecko.com/api/v3/coins/markets"

# Parametry zapytania
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 50,
    "page": 1,
    "sparkline": "false"
}

# Nagłówki
headers = {
    "accept": "application/json",
    "x-cg-demo-api-key": api_key
}

print("Pobieranie aktualnych danych rynkowych z CoinGecko API...")

# 3. Wysyłamy zapytanie do API
response = requests.get(url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()
    
    # 4. Wyciągnięcie kolumn
    crypto_data = []
    for coin in data:
        crypto_data.append({
            "Nazwa": coin["name"],
            "Symbol": coin["symbol"].upper(),
            "Cena (USD)": coin["current_price"],
            "Kapitalizacja rynkowa": coin["market_cap"],
            "Wolumen (24h)": coin["total_volume"],
            "Zmiana % (24h)": coin["price_change_percentage_24h"]
        })
        
    # 5. tabela Pandas
    df = pd.DataFrame(crypto_data)
    print(f"Sukces! Pobrano dane dla {len(df)} kryptowalut.")
else:
    print(f"Błąd połączenia z API: {response.status_code}")
    print(response.text)

# Wyświetlamy 5 pierwszych wierszy tabeli
df.head()

print("1. TOP 5 KRYPTOWALUT O NAJWIĘKSZYM WZROŚCIE (24h)")
# Sortujemy tabelę po kolumnie ze zmianą procentową malejąco
top_gainers = df.sort_values(by="Zmiana % (24h)", ascending=False).head(5)
display(top_gainers[["Nazwa", "Symbol", "Zmiana % (24h)", "Cena (USD)"]])

print("\n 2. PODSTAWOWE STATYSTYKI RYNKOWE")

display(df[["Cena (USD)", "Zmiana % (24h)"]].describe())

print("\n 3. ŁĄCZNA WARTOŚĆ TOP 50 PROJEKTÓW")
total_market_cap = df["Kapitalizacja rynkowa"].sum()
print(f"Łączna kapitalizacja tych 50 projektów to: ${total_market_cap:,.2f} USD")

Pobieranie aktualnych danych rynkowych z CoinGecko API...
Sukces! Pobrano dane dla 50 kryptowalut.
1. TOP 5 KRYPTOWALUT O NAJWIĘKSZYM WZROŚCIE (24h)

                      Nazwa Symbol  Zmiana % (24h)  Cena (USD)
41  World Liberty Financial   WLFI         2.38658    0.058910
39     Ondo US Dollar Yield   USDY         1.60273    1.150000
30            Global Dollar   USDG         0.02639    1.000000
11                     USDS   USDS         0.01340    0.999514
31               PayPal USD  PYUSD         0.01306    0.999865

 2. PODSTAWOWE STATYSTYKI RYNKOWE

         Cena (USD)  Zmiana % (24h)
count     50.000000       50.000000
mean    1409.510977       -2.198111
std     8337.411709        2.223393
min        0.000002       -7.559360
25%        0.521120       -3.874957
50%        1.013500       -2.001285
75%       46.012500       -0.060073
max    58909.000000        2.386580

 3. ŁĄCZNA WARTOŚĆ TOP 50 PROJEKTÓW
Łączna kapitalizacja tych 50 projektów to: $2,032,678,057,721.00 USD